export enum ErrorCode {
  // Authentication & Authorization
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  DEVICE_NOT_APPROVED = 'DEVICE_NOT_APPROVED',
  DEVICE_BLOCKED = 'DEVICE_BLOCKED',
  
  // Validation & General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  
  // Entity Specific
  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
  WAREHOUSE_NOT_FOUND = 'WAREHOUSE_NOT_FOUND',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  RACK_NOT_FOUND = 'RACK_NOT_FOUND',
  SHELF_NOT_FOUND = 'SHELF_NOT_FOUND',
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  FILE_RECORD_NOT_FOUND = 'FILE_RECORD_NOT_FOUND',
  BOX_NOT_FOUND = 'BOX_NOT_FOUND',
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',
  SITE_NOT_FOUND = 'SITE_NOT_FOUND',
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DUPLICATE_CODE = 'DUPLICATE_CODE',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DEPENDENCY_EXISTS = 'DEPENDENCY_EXISTS'
}
