-- AlterTable
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "column" TEXT;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "rowPrefix" TEXT;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "columnsInCell" INTEGER;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "capacityOfCell" INTEGER;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "floor" TEXT;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "isTemporaryLocation" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "rows" ADD COLUMN IF NOT EXISTS "description" TEXT;
